Fixed bug in pagemove(): incorrect G bit for paired even/odd entry. Utilities dumpfs and quotacheck corrected. /etc files modified.

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -10,7 +10,7 @@ stty status '^T'
 # Set shell to ignore SIGINT (2), but not children;
 # shell catches SIGQUIT (3) and returns to single user after fsck.
 trap : 2
-trap : 3	# shouldn't be needed
+trap : 3        # shouldn't be needed
 
 HOME=/; export HOME
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -18,40 +18,40 @@ export PATH
 
 if [ -r /fastboot ]
 then
-	echo "Fast boot: skipping disk checks."
+    echo "Fast boot: skipping disk checks."
 elif [ $1x = autobootx ]
 then
-	echo "Automatic boot in progress: starting file system checks."
-	fsck -p
-	case $? in
-	0)
-		;;
-	2)
-		exit 1
-		;;
-	4)
-		echo "Rebooting..."
-		reboot
-		echo "Reboot failed; help!"
-		exit 1
-		;;
-	8)
-		echo "Automatic file system check failed; help!"
-		exit 1
-		;;
-	12)
-		echo "Boot interrupted."
-		exit 1
-		;;
-	130)
-		# interrupt before catcher installed
-		exit 1
-		;;
-	*)
-		echo "Unknown error; help!"
-		exit 1
-		;;
-	esac
+    echo "Automatic boot in progress: starting file system checks."
+    fsck -p
+    case $? in
+    0)
+        ;;
+    2)
+        exit 1
+        ;;
+    4)
+        echo "Rebooting..."
+        reboot
+        echo "Reboot failed; help!"
+        exit 1
+        ;;
+    8)
+        echo "Automatic file system check failed; help!"
+        exit 1
+        ;;
+    12)
+        echo "Boot interrupted."
+        exit 1
+        ;;
+    130)
+        # interrupt before catcher installed
+        exit 1
+        ;;
+    *)
+        echo "Unknown error; help!"
+        exit 1
+        ;;
+    esac
 fi
 
 trap "echo 'Boot interrupted.'; exit 1" 3
@@ -60,13 +60,13 @@ swapon -a
 
 umount -a >/dev/null 2>&1
 mount -a -t nonfs
-rm -f /fastboot		# XXX (root now writeable)
+rm -f /fastboot                         # XXX (root now writeable)
 
 # set hostname, turn on network
 echo 'starting network'
 . /etc/netstart
 
-mount -a -t nfs >/dev/null 2>&1 &	# XXX shouldn't need background
+#mount -a -t nfs >/dev/null 2>&1 &      # XXX shouldn't need background
 
 # clean up left-over files
 rm -f /etc/nologin
@@ -81,38 +81,43 @@ syslogd
 # $timedflags is imported from /etc/netstart;
 # if $timedflags == NO, timed isn't run.
 if [ X${timedflags} != X"NO" ]; then
-	echo -n ', time daemon'; timed $timedflags
+    echo -n ', time daemon'; timed $timedflags
 fi
 echo '.'
 
 # /var/crash should be a directory or a symbolic link
 # to the crash directory if core dumps are to be saved.
 if [ -d /var/crash ]; then
-	echo checking for core dump...
-	savecore /var/crash
+    echo checking for core dump...
+    savecore /var/crash
 fi
 
-				echo -n 'checking quotas:'
-quotacheck -a
-				echo ' done.'
-quotaon -a
+#echo -n 'checking quotas:'
+#quotacheck -a
+#echo ' done.'
+#quotaon -a
 
 # build ps databases
 kvm_mkdb
 dev_mkdb
+
+# build password database
+if [ ! -f /etc/pwd.db ]; then
+    pwd_mkdb /etc/master.passwd
+fi
 
 chmod 666 /dev/tty[pqrs]*
 
 # check the password temp/lock file
 if [ -f /etc/ptmp ]
 then
-	logger -s -p auth.err \
-	'password file may be incorrect -- /etc/ptmp exists'
+    logger -s -p auth.err \
+        'password file may be incorrect -- /etc/ptmp exists'
 fi
 
-echo preserving editor files
-(cd /var/tmp && /usr/libexec/ex3.7preserve -a &&
-     rm -f Ex[0-9][0-9][0-9][0-9][0-9] Rx[0-9][0-9][0-9][0-9][0-9])
+#echo preserving editor files
+#(cd /var/tmp && /usr/libexec/ex3.7preserve -a &&
+#     rm -f Ex[0-9][0-9][0-9][0-9][0-9] Rx[0-9][0-9][0-9][0-9][0-9])
 
 echo clearing /tmp
 
@@ -120,50 +125,50 @@ echo clearing /tmp
 # is not needed with mfs /tmp, but doesn't hurt anything).
 (cd /tmp && rm -rf [a-km-pr-zA-Z]* &&
     find . ! -name . ! -name lost+found ! -name quotas -type d -prune \
-	-exec rm -rf -- {} \;)
+        -exec rm -rf -- {} \;)
 
-echo 'turning on accounting';	accton /var/account/acct
+#echo 'turning on accounting';  accton /var/account/acct
 
 echo -n standard daemons:
-echo -n ' update';		update
-echo -n ' cron';		cron
+echo -n ' update';              update
+#echo -n ' cron';               cron
 echo '.'
 
-echo -n starting network daemons:
+#echo -n starting network daemons:
 
 # $gated and $routedflags are imported from /etc/netstart.
 # If $gated == YES, gated is used; otherwise routed.
 # If $routedflags == NO, routed isn't run.
 if [ X${gated} = X"YES" -a -r /etc/gated.conf ]; then
-	echo -n ' gated';	gated $gatedflags
+    echo -n ' gated';           gated $gatedflags
 elif [ X${routedflags} != X"NO" ]; then
-	echo -n ' routed';	routed $routedflags
+#    echo -n ' routed';          routed $routedflags
 fi
 
-echo -n ' named';		named
+#echo -n ' named';               named
 
 # $rwhod is imported from /etc/netstart;
 # if $rwhod is set to something other than NO, rwhod is run.
 if [ ${rwhod-NO} != "NO" ]; then
-	echo -n ' rwhod';	rwhod
+#   echo -n ' rwhod';            rwhod
 fi
 
-echo -n ' printer';		lpd
+#echo -n ' printer';             lpd
 
-echo -n ' portmap';		portmap
-echo -n ' mountd';		mountd
-echo -n ' nfsd';		nfsd -u -t 6
-echo -n ' nfsiod';		nfsiod 4
+#echo -n ' portmap';             portmap
+#echo -n ' mountd';              mountd
+#echo -n ' nfsd';                nfsd -u -t 6
+#echo -n ' nfsiod';              nfsiod 4
 
-echo -n ' sendmail';		sendmail -bd -q30m
-echo -n ' inetd';		inetd
-echo -n ' amd';
-	cd /; amd -l /var/log/amd -r -a /amd -p > /var/run/amd.pid \
-	/home /etc/amd-home \
-	/n /etc/amd-n \
-	&
+#echo -n ' sendmail';            sendmail -bd -q30m
+#echo -n ' inetd';               inetd
+#echo -n ' amd';
+#   cd /; amd -l /var/log/amd -r -a /amd -p > /var/run/amd.pid \
+#   /home /etc/amd-home \
+#   /n /etc/amd-n \
+#   &
 
-echo '.'
+#echo '.'
 
 sh /etc/rc.local
 
